### ISSUE TITLE
Full-Scan fails with Gdatacyberdefenseag\\GdataAntivirus\\PluginPage\\FullScan\\RecursiveIteratorIterator" not found

### ISSUE THREAD

**Issue by unglaublicherdude** [GDATASoftwareAG/wordpress-gdata-antivirus#27]
PHP Fatal error:  Uncaught Error: Class "Gdatacyberdefenseag\\GdataAntivirus\\PluginPage\\FullScan\\RecursiveIteratorIterator" not found in /var/www/html/wp-content/plugins/gdata-antivirus/PluginPage/FullScan/FullScanMenuPage.php:137\nStack trace:\n#0 /var/www/html/wp-content/plugins/gdata-antivirus/PluginPage/FullScan/FullScanMenuPage.php(130): Gdatacyberdefenseag\\GdataAntivirus\\PluginPage\\FullScan\\FullScanMenuPage->full_scan()\n#1 /var/www/html/wp-includes/class-wp-hook.php(324): Gdatacyberdefenseag\\GdataAntivirus\\PluginPage\\FullScan\\FullScanMenuPage->full_scan_interactive('')\n#2 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#4 /var/www/html/wp-admin/admin-post.php(85): do_action('admin_post_full...')\n#5 {main}\n  thrown in /var/www/html/wp-content/plugins/gdata-antivirus/PluginPage/FullScan/FullScanMenuPage.php on line 137, referer: http://127.0.0.1:8080/wp-admin/admin.php?page=gdata-antivirus-menu-full-scan

**Comment by unglaublicherdude** [comment]
This has to be a problem with the php-scoper

**Comment by unglaublicherdude** [comment]
Will be fixed with this [commit](https://github.com/GDATASoftwareAG/wordpress-gdata-antivirus/commit/bc4aa38aa5062011d3d8d325c0a768d5ac6bbf98#diff-feb13a39f2bb0c43f4ddc3fddb7e21d3d824b4c8bb5331b37a5d291424c047e6). In release on the wordpress svn.

**Comment by unglaublicherdude** [comment]
solved with version 2.0.4
